# ==============================================================
# = Eureka Server - Profilo peer3
# ==============================================================

server:
  port: 8763
  tomcat:
    max-threads: 5

spring:
  application:
    name: EurekaServer
eureka:
  instance:
    hostname: peer1
    metadataMap:
      zone: zone1
    preferIpAddress: true
    instanceId: ${spring.application.name}-3
# ==============================================================
# = Impostazione Server
# ============================================================== 
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: false
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 30000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
# ==============================================================
# = Impostazione Client
# ============================================================== 
  client:
    serviceUrl:
      defaultZone:  http://user:BimBumBam_2018@localhost:8761/eureka/,http://user:BimBumBam_2018@localhost:8762/eureka/

# ==============================================================
# = Security Parameters
# ============================================================== 
sicurezza:
  userpwd: 'BimBumBam_2018'
  adminpwd: 'MagicaBula_2018'  
  
# ==============================================================
# = Logs Parameters
# ==============================================================        
logging:
  level:
    org:
      springframework:
        security: INFO
        cloud: DEBUG