#==========================================================
#= Configurazione PriceArt Web Service - Versione Produzione
#==========================================================
application:
  listino: 1

server:
  port: 507${seq}
 
spring:
  cache:
    type: redis
  cloud:
# ==============================================================
# = Proprietà Kafka Bus
# ==============================================================
    bus:
      #id: ${spring.application.name}:${spring.cloud.profile}:${random.uuid}
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
  kafka:
    bootstrap-servers:
    - ${KAFKA_ADDR:http://localhost:29092}
    client-id: ${spring.application.name}:${profilo}:507${seq}
# ==============================================================
# = Redis Parameters
# ==============================================================
  redis:
    connect-timeout: 2s
    host: localhost
    #password: password
    port: 6379
    timeout: 1s
# ==============================================================
# = ZipKin parameters
# ==============================================================
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
     #type: rabbit  
    message-timeout: 5
# ==============================================================
# = Sleuth parameters
# ==============================================================
  sleuth:
    sampler:
      probability: 1.0
    traceId128: false
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/Alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org:
     springframework:
      security: DEBUG
# ==============================================================
# = Parametri Sicurezza OAUTH2 con KeyCloack 
# ==============================================================
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: Alphashop
  resource: PriceArtService
  public-client: true 
# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics
# ==============================================================
# = Actuator Info
# ==============================================================
info:
  assistenza:
    nome: Nicola La Rocca
    mail: nicola_larocca@xantrix.it
    telefono: 334-12345678
    orario: 9-20
  nome:
    nome-app: PriceArt Web Service - Autenticazione OAUTH2 keycloak
  profilo: GitHub